<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Navichinna" failures="3" tests="4" name="Test" time="13.674" errors="0" timestamp="2023-12-01T10:15:23 IST">
  <testcase classname="tests.LoginTest" name="testLogin" time="1.045">
    <failure type="java.lang.AssertionError" message="Sign Out is not Present">
      <![CDATA[java.lang.AssertionError: Sign Out is not Present
at tests.LoginTest.testLogin(LoginTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase classname="tests.LoginTest" name="testLogin" time="0.923">
    <failure type="java.lang.AssertionError" message="Sign Out is not Present">
      <![CDATA[java.lang.AssertionError: Sign Out is not Present
at tests.LoginTest.testLogin(LoginTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase classname="tests.LoginTest" name="testLogin" time="3.783"/>
  <testcase classname="tests.LoginTest" name="testLogin" time="1.09">
    <failure type="java.lang.AssertionError" message="Sign Out is not Present">
      <![CDATA[java.lang.AssertionError: Sign Out is not Present
at tests.LoginTest.testLogin(LoginTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
</testsuite> <!-- Test -->
